### ISSUE TITLE
条件満たしてもコメントされない

### ISSUE THREAD

**Issue by yono** [gongo/twada-savannah#2]
発動条件満たしたはずですがライオンさんが現れませんでした

対象 issue: https://github.com/yono/songforge/pull/68
## エラーメッセージ

![d7f8b6e1a3619ddc99b6d35d8fbcefd5](https://cloud.githubusercontent.com/assets/149772/5505577/8a716eb6-87d5-11e4-82b2-24056d8dbd06.png)
## 設定内容

![db1471f716d723ae226b291546bb8c46](https://cloud.githubusercontent.com/assets/149772/5505584/97d908f2-87d5-11e4-89af-5bb862b01d84.png)

**Comment by gongo** [comment]
@yono 報告ありがとうございます！

## 結論から言うと

twada-savannah で使ってる memcached のアカウントが無効にされてました！

`twada-savannah` は webhook で飛んでくるリクエストに不正が無いかをチェックしています。
(curl で同じコメントっぽい POST リクエストを連打されても1回しか受けつけないように、とか)
で、そのチェックで「同じコメントかどうか」みたいな記憶を memcached に取っています。

今回は memcached のサービスを [memcachedcloud](https://addons.heroku.com/memcachedcloud) を利用しています

## 原因

1ヶ月ぐらい誰も twada-savannah に webhook 送信してなかったので
memcachedcloud から「お前使われてないから bucket 消すけどいいの?」ってメールきてたけど
twada-savannah が memcachedcloud 使ってるの完全に忘れててスルーしてたら
1. memcached のサーバ(bucket)が消される
2. 今日 @yono さんのあれでwebhook が送られる
3. そんなサーバはねえってエラーになる → 500 エラー

というわけでした！

現在は別のサーバ立てたので使えると思います。確認おねがいします

**Comment by yono** [comment]
@gongo 調査ありがとうございます :bow:

今回対象になったPRは既にテスト追加してしまったので、他の issue で確認しようと思います！

**Comment by yono** [comment]
確認できるまでタイムラグありそうなので（数日とか）一旦 issue 閉じます。
エラー出たら再度開きます。
対応ありがとうございました :sushi:

**Comment by gongo** [comment]
:pizza:
